CREATE TABLE IF NOT EXISTS "ASSESSMENT_TYPE" (
  "AID" INTEGER PRIMARY KEY,
  "CATEGORY" TEXT,
  "POINTS" TEXT
);
CREATE TABLE IF NOT EXISTS "COURSE_REQ"(
  "RID" INTEGER PRIMARY KEY,
  "ITEM" TEXT,
  "AID" INTEGER,
  "DUE_DATE" DATE,
  FOREIGN KEY (AID) REFERENCES ASSESSMENT_TYPE (AID)
);
CREATE TABLE IF NOT EXISTS "STUDENTS"(
  "EmplID" INTEGER PRIMARY KEY,
  "OS" TEXT
);
CREATE TABLE IF NOT EXISTS "STUDENT_SCORES"(
  "EmplID" INTEGER,
  "COURSE_REQ" INTEGER,
  "STATUS" TEXT,
  "SUBMISSION_DATE" DATE,
  "SCORE" INTEGER,
  FOREIGN KEY (COURSE_REQ) REFERENCES COURSE_REQ (RID),
  FOREIGN KEY (EmplID) REFERENCES STUDENTS (EmplID)
);
